### ISSUE TITLE
WCF Timeout Exception

### ISSUE THREAD

**Issue by mykemaas** [loraderon/nvents#1]
First, congrats on a great simple networking implementation.. it's very nice!

Now on to the gory stuff:

I set up three c# projects, one is a Windows Service, another is a simple Windows Forms project, and a third is a class library containing IEvent derived classes.  

I am running the windows service, which will occasionally send out messages to the Windows forms client via Nvents.  This works very well.  I can have any number of instances of the Windows client running and they all recieve the messages from the service.  

What goes wrong, is if any of the connected Windows Clients are disconnected, either with   Events.Unsubscribe<> or losing the network connection, roughly a minute or so later, the Windows service will exit because of the WCF TimeoutException that is thrown.  

So far, I haven't been able to find a workaround for this.  Nor have I found a way to trap the TimeoutException.  Any ideas?

**Comment by mykemaas** [comment]
Update:  

This seems to occur using the following sequence:

The server is running

Two or more clients Subscribe.

The server sends out a message.

The clients all receive the message, just fine.

One or more clients disconnect or unsubscribe.

The server sends out a message.

1 minute later, the server crashes based on the "TimeoutException"

**Comment by loraderon** [comment]
I'm quite busy this weekend (turning 30 tomorrow) but I'll take a look at this in the beginning of next week. Thanks for reporting it!

**Comment by loraderon** [comment]
Catching timeout exception when trying to publish to a disconnected client and removes that client from the list. Closed by 1abcbd2327b6b8fd1898971cf202c4bb5d09a39a

**Comment by mykemaas** [comment]
Works perfectly!  Thanks!
